name: Build and Deploy Code
on:
  [push, pull_request]
  # push:
  #   branches:
  # - "sid"
  # - "anotherbranch"
  # pull_request:
  #   branches:
  #     - "main"
  #     - "dev"

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v4
      - name: say hi to Sid
        run: echo "Hello Siddharth"
